### ISSUE TITLE
License: ISC?

### ISSUE THREAD

**Issue by nsteffens** [Gadda27/maphopper#5]
Hello Gadda27,

Could you clarify under which license this code is published? In the `package.json` you state it is under ISC license, however the repo itself does not contain a license.

Could you clarify this and maybe add the fitting license to this repo?

Thank you very much!

**Comment by olenirwing** [comment]
Hey @nsteffens,
this project was and will be continued in this [fork](https://github.com/droidsolutions/maphopper).

An MIT license was added there already.
